version: '3'
services:
  backend:
    image: robertmin/user_login:0.1.0
    ports:
      - 8000:8000
    environment:
      - CACHE_IP=memcached

  memcached:
    image: robertmin/memcached:0.1.0
    ports:
      - 11211:11211
    links:
      - backend

  frontend:
    image: robertmin/user_login_front:0.1.0
    ports:
      - 80:80